"""modified filter_article table structure

Revision ID: df03e71d60a7
Revises: j6k7l8m9n012
Create Date: 2026-02-24 18:38:09.784254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df03e71d60a7'
down_revision: Union[str, Sequence[str], None] = 'j6k7l8m9n012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_id'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_ai_provider_configs_single_active'), table_name='ai_provider_configs', postgresql_where='(is_active = true)')
    op.add_column('filter_articles', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('filter_articles_main_url_key'), 'filter_articles', type_='unique')
    op.drop_constraint(op.f('filter_articles_raw_ingestion_id_key'), 'filter_articles', type_='unique')
    op.drop_index(op.f('ix_filter_articles_sub_category_id'), table_name='filter_articles')
    op.create_index(op.f('ix_filter_articles_category_id'), 'filter_articles', ['category_id'], unique=False)
    op.drop_constraint(op.f('filter_articles_sub_category_id_fkey'), 'filter_articles', type_='foreignkey')
    op.create_foreign_key(None, 'filter_articles', 'master_category', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_column('filter_articles', 'sub_category_id')
    op.drop_constraint(op.f('uq_final_articles_post_processed_article_id'), 'final_articles', type_='unique')
    op.drop_constraint(op.f('post_processed_articles_filter_article_id_key'), 'post_processed_articles', type_='unique')
    op.drop_index(op.f('ix_raw_ingestion_pending'), table_name='raw_ingestion', postgresql_where="((status)::text = 'pending'::text)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_raw_ingestion_pending'), 'raw_ingestion', ['status', 'created_at'], unique=False, postgresql_where="((status)::text = 'pending'::text)")
    op.create_unique_constraint(op.f('post_processed_articles_filter_article_id_key'), 'post_processed_articles', ['filter_article_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_final_articles_post_processed_article_id'), 'final_articles', ['post_processed_article_id'], postgresql_nulls_not_distinct=False)
    op.add_column('filter_articles', sa.Column('sub_category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'filter_articles', type_='foreignkey')
    op.create_foreign_key(op.f('filter_articles_sub_category_id_fkey'), 'filter_articles', 'master_sub_category', ['sub_category_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_filter_articles_category_id'), table_name='filter_articles')
    op.create_index(op.f('ix_filter_articles_sub_category_id'), 'filter_articles', ['sub_category_id'], unique=False)
    op.create_unique_constraint(op.f('filter_articles_raw_ingestion_id_key'), 'filter_articles', ['raw_ingestion_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('filter_articles_main_url_key'), 'filter_articles', ['main_url'], postgresql_nulls_not_distinct=False)
    op.drop_column('filter_articles', 'category_id')
    op.create_index(op.f('ix_ai_provider_configs_single_active'), 'ai_provider_configs', ['is_active'], unique=True, postgresql_where='(is_active = true)')
    op.create_table('news',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('news', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('news_pkey'))
    )
    op.create_index(op.f('ix_news_id'), 'news', ['id'], unique=False)
    # ### end Alembic commands ###
