# app/core/constants.py

ACCESS_TOKEN_EXPIRE_MINUTES = 60
REFRESH_TOKEN_EXPIRE_DAYS = 7

PASSWORD_MIN_LENGTH = 8

AUTH_HEADER = "Authorization"
TOKEN_TYPE = "Bearer"

OTP_EXPIRY_MINUTES = 5
MAX_OTP_ATTEMPTS = 5